### ISSUE TITLE
Mixed height on rows

### ISSUE THREAD

**Issue by rendom** [vue-comps/vue-clusterize#12]
Is it not possible to have mixed heights on rows?

Example:
![screenshot_04](https://cloud.githubusercontent.com/assets/1078548/18946851/064c78cc-8631-11e6-92fb-a0c16b034964.jpg)

```
<clusterize :data="magi" auto-height>
    <div style="background:red; border-bottom: 1px solid black; height: 80px; padding-top:20px; margin-top:50px;" v-if="data.type=='header'">
        @{{data.name}}
    </div>
    <div v-else style="border-bottom: 1px solid black">
        @{{data.name}}
    </div>

    <p slot="loading">Loading...</p>
</clusterize>
```

**Comment by paulpflug** [comment]
if your groups are equally big, you could create a row per group. 
Besides of this - this is not possible.

The reason is, clusterize needs to calculate the total height to make a proper scrollbar. 
So If the height would differ, all items would be needed to load and render to determine the total height

The alternative to this is a flickering scrollbar on scrolling - but this isn't implemented in clusterize
